services:
  - type: web
    name: a-haat-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn agrihat_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: agrihat_backend.settings
